// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZIohxPuF1ReG__qZT_LQrjgAiyaxpuBA',
    appId: '1:800268694261:web:928ff712fb6dc7992b8bbc',
    messagingSenderId: '800268694261',
    projectId: 'ki-lo-3d556',
    authDomain: 'ki-lo-3d556.firebaseapp.com',
    storageBucket: 'ki-lo-3d556.firebasestorage.app',
    measurementId: 'G-1D7SGQMH2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeH_X41LRQQ2i8Xq24lvwqaqto3pRIOjU',
    appId: '1:800268694261:android:c6087f6e1452298b2b8bbc',
    messagingSenderId: '800268694261',
    projectId: 'ki-lo-3d556',
    storageBucket: 'ki-lo-3d556.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNT1bQHMmrfo_BuPaJmA_XRodHqejvtC4',
    appId: '1:800268694261:ios:ac5e677fb5ab7cbb2b8bbc',
    messagingSenderId: '800268694261',
    projectId: 'ki-lo-3d556',
    storageBucket: 'ki-lo-3d556.firebasestorage.app',
    iosBundleId: 'com.example.kiloApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNT1bQHMmrfo_BuPaJmA_XRodHqejvtC4',
    appId: '1:800268694261:ios:ac5e677fb5ab7cbb2b8bbc',
    messagingSenderId: '800268694261',
    projectId: 'ki-lo-3d556',
    storageBucket: 'ki-lo-3d556.firebasestorage.app',
    iosBundleId: 'com.example.kiloApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxQ0fO51Rs5VpIXbYuZs1lWcblSpqqHLI',
    appId: '1:800268694261:web:af0857a907e1218d2b8bbc',
    messagingSenderId: '800268694261',
    projectId: 'ki-lo-3d556',
    authDomain: 'ki-lo-3d556.firebaseapp.com',
    storageBucket: 'ki-lo-3d556.firebasestorage.app',
    measurementId: 'G-6MW9QVXNP9',
  );

}