name: kilo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  flutter_dotenv: ^5.1.0   
  google_generative_ai: 0.4.6
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_kilo.png
    - assets/images/gym_bg.jpg
    - assets/images/gym_bg_registro.jpg
    - assets/images/register_bg.png
    - assets/images/cuestionario_bg.png
    - .env

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700